name: Terraform Multi-Env CI

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

# Prevent overlapping runs
concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ---------------- DEV ----------------
  dev:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
      
      - uses: aws-actions/configure-aws-credentials@v2
        with:
           role-to-assume: arn:aws:iam::027252077892:role/iam-role
           aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: envs/dev

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: envs/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: envs/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: envs/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: envs/dev


  # ---------------- STAGING ----------------
  staging:
    runs-on: ubuntu-latest
    needs: dev
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::027252077892:role/iam-role
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: envs/staging

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: envs/staging

      - name: Terraform Validate
        run: terraform validate
        working-directory: envs/staging

      - name: Terraform Plan
        run: terraform plan
        working-directory: envs/staging

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: envs/staging


  # ---------------- PROD ----------------
  prod:
    runs-on: ubuntu-latest
    needs: staging
    environment: production
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::027252077892:role/iam-role
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: envs/prod

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: envs/prod

      - name: Terraform Validate
        run: terraform validate
        working-directory: envs/prod

      # ✅ PLAN SAVED
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: envs/prod

      # ✅ PLAN REVIEW
      - name: Show Plan
        run: terraform show tfplan
        working-directory: envs/prod

      # ✅ APPLY AFTER APPROVAL
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: envs/prod